name: Deploy dist folder
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
        # run: |
        #   echo "Cloning repo"
        #   git clone https://github.com/${{github.repository}}.git myfiles
        #   cd myfiles && ls
      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Compleated job
        run: echo "Test success"
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deployment done
        uses: echo "Deployment compleated"
