name: Greet user
# on: push
on: workflow_dispatch
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet User
        run: echo "Hello world"
      - name: bye User
        run: echo "Bye Bye!!"
